Update my

diff --git a/my b/my
--- a/my
+++ b/my
@@ -130,6 +130,49 @@ function writeConfigKey() {
     fi
 }
 
+###############################################################################
+# Get fastest url in list
+# @ - url list
+function _get_fastest() {
+  local speedlist=""
+  for I in $@; do
+    speed=$(ping -c 1 -W 5 ${I} 2>/dev/null | awk '/time=/ {print $7}' | cut -d '=' -f 2)
+    speedlist+="${I} ${speed:-999}\n"
+  done
+  fastest="$(echo -e "${speedlist}" | tr -s '\n' | sort -k2n | head -1 | awk '{print $1}')"
+  echo "${fastest}"
+}
+
+function _pat_process() {
+
+#URL="https://global.synologydownload.com/download/DSM/release/${TARGET_VERSION}/${TARGET_REVISION}${SUVP}/DSM_${DN_MODEL}_${TARGET_REVISION}.pat"
+  PATURL="${URL}"
+  PAT_FILE="${SYNOMODEL}.pat"
+  PAT_PATH="${patfile}"
+
+  SPACELEFT=$(df --block-size=1 | awk '/'${loaderdisk}'3/{print $4}') # Check disk space left
+  echo "SPACELEFT=" "${SPACELEFT}"
+  fastest=$(_get_fastest "global.synologydownload.com" "global.download.synology.com" "cndl.synology.cn")
+  mirror="$(echo ${PATURL} | sed 's|^http[s]*://\([^/]*\).*|\1|')"
+  if echo "${mirrors[@]}" | grep -wq "${mirror}" && [ "${mirror}" != "${fastest}" ]; then
+      echo "Based on the current network situation, switch to %s mirror to downloading." "${fastest}"
+      PATURL="$(echo ${PATURL} | sed "s/${mirror}/${fastest}/")"
+  fi
+  # Discover remote file size
+  FILESIZE=$(curl -k -sLI "${PATURL}" | grep -i Content-Length | awk '{print$2}')
+  if [ 0${FILESIZE} -ge 0${SPACELEFT} ]; then
+      # No disk space to download, change it to RAMDISK
+      PAT_PATH="/dev/shm/${PAT_FILE}"
+  fi
+  STATUS=$(curl -k -w "%{http_code}" -L "${PATURL}" -o "${PAT_PATH}" --progress-bar)
+  if [ $? -ne 0 -o ${STATUS} -ne 200 ]; then
+      rm -f "${PAT_PATH}"
+      echo "Check internet or cache disk space.\nError: %d" "${STATUS}"
+      exit 99
+  fi
+
+}
+
 function chkavail() {
 
     if [ $(df -h /mnt/${tcrppart} | grep mnt | awk '{print $4}' | grep G | wc -l) -gt 0 ]; then
@@ -236,14 +279,15 @@ makeimg="N"
 
 echo
 
-tcrppart="$(mount | grep -i optional | grep cde | awk -F / '{print $3}' | uniq | cut -c 1-3)3"
+loaderdisk="$(blkid | grep "6234-C863" | cut -c 1-8 | awk -F\/ '{print $3}')"
+tcrppart="${loaderdisk}3"
 
 if [ "$tcrppart" = "mmc3" ]; then
     tcrppart="mmcblk0p3"
 fi
 
 echo
-echo tcrppart is $tcrppart                                                  
+echo "loaderdisk is" "${loaderdisk}"
 echo
 
 if [ ! -d "/mnt/${tcrppart}/auxfiles" ]; then
@@ -380,12 +424,9 @@ echo
 DN_MODEL="$(echo $MODEL | sed 's/+/%2B/g')"
 echo "DN_MODEL is $DN_MODEL"
 
-#remark
-if [ 1 = 0 ]; then
 cecho p "DSM PAT file pre-downloading in progress..."
 URL="https://global.synologydownload.com/download/DSM/release/${TARGET_VERSION}/${TARGET_REVISION}${SUVP}/DSM_${DN_MODEL}_${TARGET_REVISION}.pat"
 cecho y "$URL"
-fi
 patfile="/mnt/${tcrppart}/auxfiles/${SYNOMODEL}.pat"                                         
 
 if [ "$TARGET_VERSION" = "7.2" ]; then
@@ -399,25 +440,28 @@ fi
 #   sudo rm -rf /home/tc/redpill-load/custom/extensions/reboottotcrp
 #fi   
         
-if [ -f ${patfile} ]; then                                                               
+if [ -f ${patfile} ]; then
     cecho r "Found locally cached pat file ${SYNOMODEL}.pat in /mnt/${tcrppart}/auxfiles"
     cecho b "Downloadng Skipped!!!"
 st "download pat" "Found pat    " "Found ${SYNOMODEL}.pat"
 else
 
-  #remark
-  if [ 1 = 0 ]; then
     chkavail
     if [ $avail_num -le 390 ]; then
         echo "No adequate space on ${local_cache} to download file into cache folder, clean up PAT file now ....."
         rm -f ${local_cache}/*.pat
     fi
 st "download pat" "Downloading pat  " "${SYNOMODEL}.pat"        
+
+  if [ 1 = 0 ]; then
     STATUS=`curl --insecure -w "%{http_code}" -L "${URL}" -o ${patfile} --progress-bar`
     if [ $? -ne 0 -o ${STATUS} -ne 200 ]; then
        echo  "Check internet or cache disk space"
        exit 99
     fi
+  else
+    _pat_process    
+  fi
 
     os_sha256=$(sha256sum ${patfile} | awk '{print $1}')                                
     cecho y "Pat file  sha256sum is : $os_sha256"                                       
@@ -434,10 +478,11 @@ st "download pat" "Downloading pat  " "${SYNOMODEL}.pat"
         cecho y "os sha256 verify FAILED, check ${patfile}  "                           
         exit 99                                                                         
     fi
-  fi
 fi
 
-
+cecho p "press any key to continue..."
+read answer
+exit 0
 
 echo
 cecho g "Loader Building in progress..."
@@ -470,7 +515,7 @@ if [ $? -ne 0 ]; then
     ./rploader.sh clean
 fi
 
-echo "Clean all PAT files for saving space!"
-sudo rm -f /mnt/${tcrppart}/auxfiles/*.pat
+#echo "Clean all PAT files for saving space!"
+#sudo rm -f /mnt/${tcrppart}/auxfiles/*.pat
 
 exit 0
